"""
Django settings for carpooling project.

Generated by 'django-admin startproject' using Django 3.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from __future__ import annotations

import os
import sys
from os.path import abspath
from os.path import basename
from os.path import dirname
from os.path import join
from os.path import normpath
from pathlib import Path

from lib.utils import convert_str_bool
from lib.utils import getenv

# fetch Django's project directory
DJANGO_ROOT = dirname(dirname(abspath(__file__)))

# fetch the project_root
PROJECT_ROOT = dirname(DJANGO_ROOT)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = convert_str_bool(getenv('DJANGO_DEBUG'), True)

ALLOWED_HOSTS = []
# Add hosts from env variable, default to "*"
for v in getenv('DJANGO_ALLOWED_HOSTS', '*').split(','):
    v = v.strip()
    if v:
        ALLOWED_HOSTS.append(v)


# Set static files config
STATIC_URL = 'static/'
STATIC_ROOT = 'staticfiles/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cjwun1jlw9onag=1k1nrgnajvoc8()x2oif_mq$3maun(zbb-b'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',
    'website',
    'crispy_forms',
    'crispy_bootstrap4',
]

 
CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# add apps/ to the Python path
sys.path.append(normpath(join(PROJECT_ROOT, 'apps')))

# Set URLs root path
ROOT_URLCONF = 'bootstrap.urls'

# Set templates folder root path
PROJECT_TEMPLATES = [join(PROJECT_ROOT, 'templates')]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': PROJECT_TEMPLATES,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bootstrap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

# Authentication Backend Models
AUTHENTICATION_BACKENDS = (
    'website.backends.OrangeAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
########################################################################################

######################
# Orange Auth Config #
######################
ORANGE_AUTH_URL = os.getenv(
    'ORANGE_AUTH_URL', 'https://inside01.api.intraorange/openidconnect/internal/v1/token',
)
ORANGE_AUTH_USER_INFO_URL = os.getenv(
    'ORANGE_AUTH_USER_INFO_URL', 'https://inside01.api.intraorange/openidconnect/internal/v1/userinfo',
)
<<<<<<< bootstrap/settings/common.py
# ORANGE_AUTH_REDIRECT_URI = os.getenv('ORANGE_AUTH_REDIRECT_URI')
# ORANGE_AUTH_HEADER = os.getenv('ORANGE_AUTH_HEADER')
# ORANGE_AUTH_CLIENT_ID = os.getenv('ORANGE_AUTH_CLIENT_ID')

ORANGE_AUTH_REDIRECT_URI = 'http://carpool.localhost:8000/login/'
ORANGE_AUTH_HEADER = 'Basic OUFkY0tWbWNKaEExa3FSRzFjVXF6NWFYR2l1OGlUcEk6ZlUzTmQ1ZFlsVm9Yc3Bhdg=='
ORANGE_AUTH_CLIENT_ID = '9AdcKVmcJhA1kqRG1cUqz5aXGiu8iTpI'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'EG'

ORANGE_AUTH_REDIRECT_URI = os.getenv('ORANGE_AUTH_REDIRECT_URI')
ORANGE_AUTH_HEADER = os.getenv('ORANGE_AUTH_HEADER')
ORANGE_AUTH_CLIENT_ID = os.getenv('ORANGE_AUTH_CLIENT_ID')


# ---------------------------------------------------------------------
# Sending Email Configuration
ORANGE_SEND_EMAIL_CLIENT_ID = os.environ.get(
    'ORANGE_SEND_EMAIL_CLIENT_ID', 'cli-ocapapp-v1-prd',
)

ORANGE_SEND_EMAILS_CLIENT_SECRET = os.environ.get(
    'ORANGE_SEND_EMAILS_CLIENT_SECRET', 'NjA4ODk1ODExZGFlMDg3ZjBhYmZkNzdiMjc1NDE2YTc1MzRkZTc4ZjRkOTM2NDNkZDFiNjY0YjY4MmJkMjlkZGuipaE19T417drEigbHlqwISzzsr1LuOu1XuOBlCAb7',
)

SEND_MAILS_ACCESS_TOKENS_URL = os.environ.get(
    'SEND_MAILS_ACCESS_TOKENS_URL', 'https://okapi-v2.api.hbx.geo.infra.ftgroup/v2/token',
)

SEND_MAIL_SERVICE_URL = os.environ.get(
    'SEND_MAIL_SERVICE_URL', 'https://mail2fed.preprod.api.hbx.geo.infra.ftgroup/v1/email/send',
)

SENDER_EMAIL = os.environ.get('SENDER_EMAIL', 'webex.monitor@orange.com')


ORANGE_MAIL_API_CERT = join(
    BASE_DIR, 'certs/Groupe_France_Telecom_Root_CA.pem',
)

