# Generated by Django 4.1.9 on 2023-08-31 16:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.website.models.CarRegistration
import apps.website.models.profile


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "CarReg_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("No_OF_Seats", models.IntegerField(default="3")),
                ("Car_Manufacture", models.CharField(max_length=50)),
                ("Car_Color", models.CharField(max_length=50)),
                ("Car_license", models.BooleanField(blank=True, default=False)),
                ("Driver_license", models.BooleanField(blank=True, default=False)),
                ("Engine_size", models.IntegerField(blank=True, default="0")),
                ("No_clyender", models.IntegerField(blank=True, default="0")),
                ("Fuel_consumption", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CarPlate",
            fields=[
                (
                    "CarPlate_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "Number",
                    models.IntegerField(
                        validators=[apps.website.models.CarRegistration.CarPlate.validate_length]
                    ),
                ),
                ("Letter_one", models.CharField(blank=True, max_length=1)),
                ("Letter_two", models.CharField(max_length=1)),
                ("Letter_three", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("To Office", "To Office"),
                            ("From Office", "From Office"),
                            ("2-Way Ride", "2-Way Ride"),
                        ],
                        default="To Office",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("leave_time", models.TimeField()),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("no_of_seats", models.IntegerField(default="3")),
                ("restrictions", models.CharField(blank=True, max_length=100, null=True)),
                ("meeting_point", models.CharField(blank=True, max_length=300, null=True)),
                ("Car_Pallet_Number", models.CharField(blank=True, max_length=50)),
                ("distance", models.IntegerField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="car", to="website.car"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RidesBooked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Pending"), ("2", "Accepted"), ("3", "Rejected"), ("4", "Cancelled")],
                        default="1",
                        max_length=50,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "RideRequested",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.ride"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=50, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], default="Male", max_length=6
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                ("profile_pic", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "legal_consent_date",
                    models.DateField(default=apps.website.models.profile.Profile.six_months_from_today),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="Car_Pallet_Number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="plate", to="website.carplate"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="Owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
