# Generated by Django 4.1.9 on 2023-07-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import apps.website.models.CarRegistration


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "CarReg_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("No_OF_Seats", models.IntegerField(default="3", max_length=10)),
                ("Car_Manufacture", models.CharField(max_length=50)),
                ("Car_Color", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CarPlate",
            fields=[
                (
                    "CarPlate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "Number",
                    models.IntegerField(
                        validators=[
                            apps.website.models.CarRegistration.CarPlate.validate_length
                        ]
                    ),
                ),
                ("Letter_one", models.CharField(blank=True, max_length=1)),
                ("Letter_two", models.CharField(max_length=1)),
                ("Letter_three", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("To Office", "To Office"),
                            ("From Office", "From Office"),
                            ("2-Way Ride", "2-Way Ride"),
                        ],
                        default="To Office",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("leave_time", models.TimeField()),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("no_of_seats", models.IntegerField(default="3")),
                (
                    "restrictions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meeting_point",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("Car_Pallet_Number", models.CharField(blank=True, max_length=50)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car",
                        to="website.car",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=50, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=6,
                    ),
                ),
                ("city", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="Car_Pallet_Number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plate",
                to="website.carplate",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="Owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
