# Generated by Django 4.2.1 on 2023-06-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
  
                    migrations.CreateModel(
            name='Car',
            fields=[
                ('CarReg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('No_OF_Seats', models.IntegerField(max_length=10)),
                ('Car_Pallet_Number', models.IntegerField(max_length=10)),
                ('Car_Manufacture', models.CharField(max_length=50)),
                ('Car_Color', models.CharField(max_length=50)),
            ],
        ),
           
        migrations.AddField(
            model_name='car',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.profile', unique=True),
        ),
    ]
