# Generated by Django 4.1.9 on 2023-07-04 06:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_profile_car_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarPlate",
            fields=[
                (
                    "CarPlate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("Number", models.IntegerField(max_length=5)),
                ("Letter_one", models.CharField(max_length=1)),
                ("Letter_two", models.CharField(max_length=1)),
                ("Letter_three", models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="Car_Pallet_Number",
            field=models.ForeignKey(
                max_length=10,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.carplate",
            ),
        ),
    ]
