# Generated by Django 4.2.1 on 2023-06-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_delete_ride_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile'),
        ),
    ]
