# Generated by Django 4.1.9 on 2023-09-11 11:07

import apps.website.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_car_engine_size_remove_car_fuel_consumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="legal_consent_date",
            field=models.DateField(default=apps.website.models.profile.six_months_from_today),
        ),
    ]
