# Generated by Django 4.1.9 on 2023-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
