# Generated by Django 4.1.9 on 2023-07-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_carplate_alter_car_car_pallet_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="Car_Pallet_Number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.carplate"
            ),
        ),
    ]
