# Generated by Django 4.1.9 on 2023-07-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_ridesbooked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridesbooked",
            name="RideRequested",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.ride"),
        ),
    ]
