# Generated by Django 4.1.9 on 2023-07-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_ridesbooked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridesbooked",
            name="RideRequested",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.ride"
            ),
        ),
    ]
