# Generated by Django 4.1.9 on 2023-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_ridesbooked_riderequested"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
