# Generated by Django 4.1.9 on 2023-07-04 13:14

from django.db import migrations, models
import website.models.CarRegistration


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_car_no_of_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carplate",
            name="Number",
            field=models.IntegerField(
                validators=[website.models.CarRegistration.CarPlate.validate_length]
            ),
        ),
    ]
