# Generated by Django 4.1.9 on 2023-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridesbooked",
            name="comment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ridesbooked",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="No_OF_Seats",
            field=models.IntegerField(default="3"),
        ),
    ]
