# Generated by Django 4.1.9 on 2023-07-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_carplate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carplate",
            name="Letter_one",
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
