# Generated by Django 4.1.9 on 2023-08-25 10:16

import apps.website.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="legal_consent_date",
            field=models.DateField(
                default=apps.website.models.profile.Profile.six_months_from_today
            ),
        ),
    ]
