# Generated by Django 4.1.9 on 2023-07-13 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0007_alter_carplate_letter_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("To Office", "To Office"),
                            ("From Office", "From Office"),
                            ("2-Way Ride", "2-Way Ride"),
                        ],
                        default="To Office",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("leave_time", models.TimeField()),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("no_of_seats", models.IntegerField(default="3")),
                (
                    "restrictions",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meeting_point",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.car"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
