# Generated by Django 4.1.9 on 2023-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_ridesbooked_comment_ridesbooked_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridesbooked",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Pending"),
                    ("2", "Accepted"),
                    ("3", "Rejected"),
                    ("4", "Cancelled"),
                ],
                default="1",
                max_length=50,
            ),
        ),
    ]
