# Generated by Django 4.1.9 on 2023-07-13 10:11

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_ride_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="area",
            field=models.CharField(blank=True, null=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, null=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ride",
            name="area",
            field=models.CharField(blank=True, null=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ride",
            name="city",
            field=models.CharField(blank=True, null=True, max_length=50),
        ),
    ]
