# Generated by Django 4.1.9 on 2023-07-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_ride_id_alter_car_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="Car_Pallet_Number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plate",
                to="website.carplate",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="website.car",
            ),
        ),
    ]
