# Generated by Django 4.1.9 on 2023-08-31 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0009_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ridesbooked",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Pending"),
                    ("2", "Accepted"),
                    ("3", "Rejected"),
                    ("4", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
