# Generated by Django 4.1.9 on 2023-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_car_car_pallet_number_alter_ride_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="Car_Pallet_Number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
