# Generated by Django 4.1.9 on 2023-08-31 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_profile_legal_consent_date"),
        ("website", "0013_alter_car_car_license_alter_car_driver_license"),
    ]

    operations = []
