# Generated by Django 4.1.9 on 2023-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_merge_20230831_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="Engine_size",
            field=models.IntegerField(blank=True, default="0"),
        ),
        migrations.AddField(
            model_name="car",
            name="Fuel_consumption",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="No_clyender",
            field=models.IntegerField(blank=True, default="0"),
        ),
        migrations.AddField(
            model_name="ride",
            name="distance",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
