# Generated by Django 4.1.9 on 2023-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="distance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
