# Generated by Django 4.1.9 on 2023-08-31 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_profile_user_alter_ridesbooked_status"),
        ("website", "0017_alter_ride_distance"),
    ]

    operations = []
